[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/huggingface/*"
  to = "https://router.huggingface.co/hf-inference/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/hf-chat/*"
  to = "https://router.huggingface.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
